### PR TITLE
[WBCAMS-570] fix quiz question hanging indent

### PR DESCRIPTION
**Pull request by jonathan-longe**
Hanging indent fixed as shown below.

Screenshot (135)

Note, there are some circumstances where the required red asterisk ("*") will drop down onto the following line if there's not enough space on the preceding line.  Like this:

Screenshot (136)

### CODE REVIEW

**Comment by jonathan-longe** [comment]
Hold off approving this please.  Just noticed an issue with some layouts

**Comment by jonathan-longe** [comment]
@infojunkie and @rjkuyvenhoven apologies for the delay.  This PR is now ready for your review.

**Comment by infojunkie** [comment]
Thanks @jonathan-longe would you mind including a desktop screenshot as well? The original report was made on desktop unless I am misinterpreting the screenshots that UAT attached.

**Comment by infojunkie** [comment]
Also, the client is requesting to remove the red asterisk that indicates a required field. Thanks!

**Comment by jonathan-longe** [comment]
Screenshot showing theme as seen by desktop user.  Note the asterisks have been removed.
Screenshot (138)

**Review by infojunkie — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
