### PR TITLE
[WBCAMS-549] fix print theme

### PR DESCRIPTION
**Pull request by jonathan-longe**
## Compare Careers page:

Screenshot (122)

## Results pages:

Screenshot (119)
Screenshot (120)
Screenshot (121)

### CODE REVIEW

**Comment by infojunkie** [comment]
I'll let @rjkuyvenhoven do the review. Thanks!

**Comment by rjkuyvenhoven** [comment]
The results page is missing the subtitle "Find out about your key aptitudes..."

I guess the question is how closely do we want to match PROD.  These results show the same information and structure as the PROD print.  However, there are some sizing and alignment variations.

Some of the sizing changes (ie. results table) seem acceptable, while the Top Aptitudes card sizing may not be.

**Comment by infojunkie** [comment]
> The results page is missing the subtitle "Find out about your key aptitudes..."
> 
> I guess the question is how closely do we want to match PROD. These results show the same information and structure as the PROD print. However, there are some sizing and alignment variations.
> 
> Some of the sizing changes (ie. results table) seem acceptable, while the Top Aptitudes card sizing may not be.

From my perspective, as long as we have more time to work on the theme, we can get closer to the original theme.

**Comment by jonathan-longe** [comment]
> The results page is missing the subtitle "Find out about your key aptitudes..."
> 
> I guess the question is how closely do we want to match PROD. These results show the same information and structure as the PROD print. However, there are some sizing and alignment variations.
> 
> Some of the sizing changes (ie. results table) seem acceptable, while the Top Aptitudes card sizing may not be.

Thanks Ray, I'll add the missing subtitle and, if time permits, get the theme closer to the original.

**Comment by jonathan-longe** [comment]
@rjkuyvenhoven do you have any objection if I merge this PR?  I'd like these changes to be visible to Geethu so I don't hold up her testing.

**Comment by rjkuyvenhoven** [comment]
> @rjkuyvenhoven do you have any objection if I merge this PR? I'd like these changes to be visible to Geethu so I don't hold up her testing.

that's ok with me

**Pull request merged**
