### PR TITLE
Add unthemed icon to career match in Interests quiz

### PR DESCRIPTION
**Pull request by infojunkie**

### CODE REVIEW

**Comment by infojunkie** [comment]
@jonathan-longe , I've added the missing information icon to the "Your Match" column for Interests quiz results.

I also had to fix the column labels in mobile, to read them from the view settings instead of hard-coding them.

This is how the icon looks unthemed on desktop and mobile:
screenshot-workbc-cc_docker_localhost_8000-2024_09_11-16_52_44

Screenshot from 2024-09-11 16-53-16

**Comment by jonathan-longe** [comment]
@infojunkie as mentioned in the Teams theming thread, for some reason I'm not able to generate Interest Quiz results on my local.  I either get the following error:

Screenshot (127)

or this:

Screenshot (128)

Here's the steps that I followed:

- pull this branch
- delete database using drush
- import `workbc-cc.sql` from branch using drush
- run sync.sh and except all configuration changes
- run `docker-compose down`
- run `docker-compose up`

I followed your suggestion to monitor the Postgres container for errors while refreshing the results page but I don't see any database errors.

I can complete other quizzes (specifically the Work Values Quiz and the Abilities Quiz) without any errors.

Can help me by explaining what's different about the way the Interests Quiz generates results compared to the other quizzes?

**Comment by infojunkie** [comment]
I meant the Drupal log, sorry.
Screenshot from 2024-09-11 20-32-27

**Comment by jonathan-longe** [comment]
Reduced the size of the SVG image in the desktop view:

Screenshot (129)

The mobile rendering still looks okay -- no change required

Screenshot (131)

**Comment by infojunkie** [comment]
MicrosoftTeams-image

Thanks @jonathan-longe but I think the spacing on PROD version looks slightly more pleasing to the eye on desktop.

**Comment by infojunkie** [comment]
Also, @jonathan-longe please review the tooltip window itself.

**Comment by jonathan-longe** [comment]
> Thanks @jonathan-longe but I think the spacing on mobile looks cramped and the icon disproportioned. I'm including the PROD version for reference.

On it.  Thanks for feedback!

**Comment by jonathan-longe** [comment]
> MicrosoftTeams-image
> 
> Thanks @jonathan-longe but I think the spacing on mobile looks cramped and the icon disproportioned. I'm including the PROD version for reference.

I think you might be mixing up the desktop and mobile theming.  The screenshot above is from the desktop theme.  I believe the mobile themes are identical.  Here's how it looks like on PROD from your screenshot copied from above:

Screenshot from 2024-09-11 16-53-16

And, here's how it looks using the changes in this PR (my screenshot copied from above):

Screenshot (131)

Let me know if you think either the desktop or mobile theme's require more space between the text, "You Match" and the SVG image.

The popup still needs theming -- thanks for noticing that!

**Comment by infojunkie** [comment]
@jonathan-longe the 2 images that you included in your latest comment are from our branch, and they now indeed look identical, which is good progress.

However, your statement:

> Here's how it looks like on PROD from your screenshot copied from above:

is not accurate, because the screenshot in question is actually from our branch. The screenshot from PROD that I included in my earlier comment features the tooltip window open. And in this one, the spacing between the words "Your Match" and the information icon is wider than the spacing in ours.

It's not a big deal, and certainly not a deal-breaker, but good to be aligned on what we're seeing.

**Comment by jonathan-longe** [comment]
> MicrosoftTeams-image
> 
> Thanks @jonathan-longe but I think the spacing on mobile looks cramped and the icon disproportioned. I'm including the PROD version for reference.

Agreed, let's get aligned on what we're fixing.  I'm confused as to whether we're fixing the spacing in mobile or desktop.  The image above is from the desktop theme, but comment states, "...the spacing on mobile looks cramped ...".

**Comment by infojunkie** [comment]
> I'm confused as to whether we're fixing the spacing in mobile or desktop.

Now that you made the spacing on desktop to be exactly the same as on mobile, my comment would apply to both, in contrast to how it looks on PROD.

**Comment by jonathan-longe** [comment]
> ... my comment would apply to both, in contrast to how it looks on PROD.

Great, let's review the mobile view first.  Here's how it looks in PROD:

PROD

And, here's how it looks after applying this PR:

PR_296

I can't see a difference between these two screenshots with respect to the space between the text, "Your Match" and the SVG image.

**Comment by infojunkie** [comment]
Thanks for clarifying! It all makes sense now.

**Comment by jonathan-longe** [comment]
@infojunkie the Magnific Popup library appears to be deprecated. I propose we use Bootstrap tooltips instead. This does change the way the popup appears.  Below are two example from my local showing the Bootstrap version.

Screenshot from 2024-09-12 17-46-46

Screenshot from 2024-09-12 17-51-34

For comparison, here's how the tooltips appears on PROD:

Screenshot (137)

**Comment by infojunkie** [comment]
I think the Bootstrap tooltips look much better! Go for it.

**Pull request merged**
